import Head from "next/head";
import Aside from "../components/aside";
import Loading from "../components/loading";
import NewsSection from "../components/newsSection";
import { graphcms, queryHomePage } from "../services/api";

export async function getStaticProps() {
  const { posts, categories } = await graphcms.request(queryHomePage);
  return {
    props: {
      posts,
      categories,
    },
  };
}

export default function Home({ posts, categories }) {
  return (
    <div>
      <Head>
        <title>My Personal Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {!posts.length && <Loading />}
      <main className="container flex-container">
        <NewsSection posts={posts} />
        <Aside posts={posts} categories={categories} />
      </main>
    </div>
  );
}
